apiVersion: apps/v1
kind: Deployment
metadata:
  name: facservice
  namespace: fac
spec:
  selector:
    matchLabels:
      app: facservice
  replicas: 1
  template:
    metadata:
      labels:
        app: facservice
    spec:
      containers:
        - name: facservice-pod
          image: vsimone67/facservice:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 360
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-facservice
              - secret:
                  name: appsettings-secret-facservice
---
apiVersion: v1
kind: Service
metadata:
  name: facservice-svc
  namespace: fac
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: facservice
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: facservice-route
  namespace: fac
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/fac/{catchall}`)
      kind: Rule
      services:
        - name: facservice-svc
          port: 80
    - match: PathPrefix(`/facservice/health`)
      kind: Rule
      services:
        - name: facservice-svc
          port: 80
      middlewares:
        - name: st-healthcheck
    - match: PathPrefix(`/facservice/metrics`)
      kind: Rule
      services:
        - name: facservice-svc
          port: 80
      middlewares:
        - name: st-metrics
